In [1]:
import numpy as np

In [3]:
#1차원 배열(list)로 numpy 배열 생성
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
#2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
#배열 생성 및 초기화
a = np.zeros(10) #주어진 형태와 타입을 알고, 그것을 0으로 채움
b = np.zeros((3,3))
c = np.ones(10) #주어진 형태와 타입을 알고, 그것을 1로 채움
d = np.ones((3,3))
e = np.full((3,3), 1.5) #주어진 형태를 알고, 그것을 특정한 값으로 채움
f = np.eye(3) #정사각형 행렬 생성, 주 대각선의 원소가 모두 1이고, 나머지는 모두 0

pr_list = [a,b,c,d,e,f]

for i in pr_list:
    print(i)
    print("")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [2]:
#np.arange(시작, 끝+1, 간격) -> 정수 범위로 배열 생성
a = np.arange(1, 21)
b = np.arange(1, 21, 2)
print(a)
print("")
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 1  3  5  7  9 11 13 15 17 19]


In [4]:
#np.linspace(시작, 끝, 개수) -> 범위 내에서 균등 간격의 '개수' 개의 배열 생성
a = np.linspace(1, 20, 5)
b = np.linspace(0, 10, 5)
print(a)
print("")
print(b)

[ 1.    5.75 10.5  15.25 20.  ]

[ 0.   2.5  5.   7.5 10. ]


In [6]:
#np.logspace(np.log(시작), np.log(끝), 개수) -> 로그 범위 내에서 균등 배열 생성
a = np.logspace(np.log10(10), np.log10(100), 5)
b = np.logspace(1, 2, 5)
print(a)
print("")
print(b)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [7]:
#random(사이즈) -> 랜덤한 수의 배열 생성
a = np.random.random()
b = np.random.random((4,4))
print(a)
print("")
print(b)

0.7390524616354992

[[0.78607198 0.31421036 0.48126903 0.31266258]
 [0.01836328 0.56862556 0.79923629 0.06267364]
 [0.27600189 0.05057944 0.95043681 0.37916632]
 [0.62454584 0.12098646 0.60969578 0.49041525]]


In [9]:
#randint(시작, 끝, 사이즈) -> 랜덤한 "정수"의 배열 생성
a = np.random.randint(1,10)
b = np.random.randint(1,10,(4,4))
print(a)
print("")
print(b)

9

[[6 6 1 3]
 [8 8 6 5]
 [7 4 3 9]
 [6 9 8 1]]


In [12]:
#rand(d0, d1, d2,...,dn) -> 크기가 (d0 ~ dn)인 배열 생성 후 난수로 초기화: "균등분포"를 고려
a = np.random.rand(3,3)
print(a)

[[0.65116683 0.08713583 0.16999748]
 [0.43893648 0.15132636 0.92755323]
 [0.3584053  0.63137132 0.01350276]]


In [13]:
#randn(d0, d1, d2,...,dn) -> 크기가 (d0 ~ dn)인 배열 생성 후 난수로 초기화: "정규분포"를 고려
a = np.random.randn(3,3)
print(a)

[[-0.19423223  0.36438403  0.94198471]
 [-0.16303066  0.2927649   0.95127289]
 [ 1.26538604 -2.34578987  0.42121858]]
