In [1]:
import numpy as np

In [3]:
#1차원 배열(list)로 numpy 배열 생성
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
#2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
#배열 생성 및 초기화
a = np.zeros(10) #주어진 형태와 타입을 알고, 그것을 0으로 채움
b = np.zeros((3,3))
c = np.ones(10) #주어진 형태와 타입을 알고, 그것을 1로 채움
d = np.ones((3,3))
e = np.full((3,3), 1.5) #주어진 형태를 알고, 그것을 특정한 값으로 채움
f = np.eye(3) #정사각형 행렬 생성, 주 대각선의 원소가 모두 1이고, 나머지는 모두 0

pr_list = [a,b,c,d,e,f]

for i in pr_list:
    print(i)
    print("")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [2]:
#np.arange(시작, 끝+1, 간격) -> 정수 범위로 배열 생성
a = np.arange(1, 21)
b = np.arange(1, 21, 2)
print(a)
print("")
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 1  3  5  7  9 11 13 15 17 19]


In [4]:
#np.linspace(시작, 끝, 개수) -> 범위 내에서 균등 간격의 '개수' 개의 배열 생성
a = np.linspace(1, 20, 5)
b = np.linspace(0, 10, 5)
print(a)
print("")
print(b)

[ 1.    5.75 10.5  15.25 20.  ]

[ 0.   2.5  5.   7.5 10. ]


In [6]:
#np.logspace(np.log(시작), np.log(끝), 개수) -> 로그 범위 내에서 균등 배열 생성
a = np.logspace(np.log10(10), np.log10(100), 5)
b = np.logspace(1, 2, 5)
print(a)
print("")
print(b)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [7]:
#random(사이즈) -> 랜덤한 수의 배열 생성
a = np.random.random()
b = np.random.random((4,4))
print(a)
print("")
print(b)

0.7390524616354992

[[0.78607198 0.31421036 0.48126903 0.31266258]
 [0.01836328 0.56862556 0.79923629 0.06267364]
 [0.27600189 0.05057944 0.95043681 0.37916632]
 [0.62454584 0.12098646 0.60969578 0.49041525]]


In [9]:
#randint(시작, 끝, 사이즈) -> 랜덤한 "정수"의 배열 생성
a = np.random.randint(1,10)
b = np.random.randint(1,10,(4,4))
print(a)
print("")
print(b)

9

[[6 6 1 3]
 [8 8 6 5]
 [7 4 3 9]
 [6 9 8 1]]


In [12]:
#rand(d0, d1, d2,...,dn) -> 크기가 (d0 ~ dn)인 배열 생성 후 난수로 초기화: "균등분포"를 고려
a = np.random.rand(3,3)
print(a)

[[0.65116683 0.08713583 0.16999748]
 [0.43893648 0.15132636 0.92755323]
 [0.3584053  0.63137132 0.01350276]]


In [13]:
#randn(d0, d1, d2,...,dn) -> 크기가 (d0 ~ dn)인 배열 생성 후 난수로 초기화: "정규분포"를 고려
a = np.random.randn(3,3)
print(a)

[[-0.19423223  0.36438403  0.94198471]
 [-0.16303066  0.2927649   0.95127289]
 [ 1.26538604 -2.34578987  0.42121858]]


### 넘파이 표준 데이터 타입
- np.int32/64 -> 64비트 정수 타입
- np.float32/64 -> 32비트 부동 소수 타입
- np.bool -> 부울형(True, False)
- np.object -> 파이썬 객체 타입
- np.comflex -> 복소수(128float)

In [6]:
#배열의 속성
arr = np.arange(1,6)
print(arr)
print('ndim:', arr.ndim) # 배열 차원 수 또는 배열 축의 수
print('shape:', arr.shape) # 배열 각 차원의 크기를 튜플 형태로 표현
print('dtype:', arr.dtype) #배열 내 원소의 데이터형
print('size:', arr.size) #배열 원소의 개수
print('itemsize:', arr.itemsize) # 배열 내 원소의 크기를 바이트 단위로 기술
print('nbytes:', arr.nbytes) #배열 전체 바이트

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40


In [7]:
#1차원 배열의 인덱싱 및 변경
a1 = np.arange(9) #1차원 배열
print(a1)
print(a1[0])
print(a1[-1])
a1[0] = 10 #요소변경
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [9]:
#2차원 배열의 인덱싱 및 변경
a2 = np.arange(9).reshape((3,3)) #2차원 배열
print(a2)
print(a2[0,1]) #1행 두 번째 컬럼 요소 참조
print(a2[1,2]) #2행 세 번째 컬럼 요소 참조
a2[0,0] = 10 #1행 첫 번째 컬럼 업데이트
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


### 배열의 슬라이싱
- 범위 지정에서 시작 인덱스가 생략될 경우 = 0으로 간주
- 종료 인덱스가 생략될 경우 = -1(마지막 인덱스)로 간주
- ':' 형태로 지정된 범위는 전체 범위
- 시작 인덱스와 종료 인덱스에 음수를 지정 -> 반대 방향

In [10]:
#1차원 배열의 슬라이싱
a1 = np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2])
print(a1[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [13]:
#2차원 배열의 슬라이싱
a2 = np.arange(1, 25).reshape((4,6))
print(a2)
print(a2[1])
print(a2[1:3, 1:5])
print(a2[2,:])
print(a2[:3, :3])
print(a2[2:,::-1])
print(a2[::-1,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [16]:
#불리언 인덱싱 개념
a = np.arange(1,6)
print(a)
b = [True, False, False, True, False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [18]:
#불리언 인덱싱: 비교 연산자 사용
a = np.arange(11)
print(a[a<5])
five_up = (a>=5)
five_up
print(a[five_up])
divide_by_2 = a[a%2 == 0]
print(divide_by_2)

[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [19]:
#불리언 인덱싱: 관계 연산자 사용

#논리 연산자 사용 (& | ~)
c = a[(a > 5) & (a < 11)] #and
print(c)
d = a[(a > 9) | (a < 5)] # or
print(d)
e = a[~(a % 3 == 0)] #not
print(e)

[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


In [20]:
#배열의 산술 연산: 사칙연산 연산자와 함수 활용
a = np.arange(1,11)
b = np.arange(1,11)
print(a+b)
print(np.add(a,b)) #덧셈 함수
print(a-b)
print(np.subtract(a,b)) # 뺄셈 함수
print(a*b)
print(np.multiply(a,b)) #곱셈 함수
print(a/b)
print(np.divide(a,b)) #나눗셈 함수

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
#기타 연산: 지수/제곱근/sin/cos/tan/log
a = np.arange(1,11)
print(np.exp(a)) # 지수
print(np.sqrt(a)) #제곱근
print(np.sin(a)) #sin
print(np.cos(a)) #cos
print(np.tan(a)) #tan
print(np.log(a)) #log

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


### 집계 함수
- 집계 함수는 축(axis)을 기준으로 계산
- axis 지정 X -> axis = None
- case1: axis = None
  전체 행렬을 하나의 배열로 간주하고, 집계 함수의 범위를 전체 행렬로 정의
- case2: axis = 0
  행(세로)을 기준으로 각 행의 동일 인덱스의 요소를 그룹으로 함.
  각 그룹을 집계 함수의 범위로 정의
- case3: axis = 1
  열(가로)를 기준으로 각 열의 요소를 그룹으로 함.
  각 그룹을 집계 함수의 범위로 정의

In [23]:
#합계: [ndarray 배열 객체].sum(), np.sim()
a = np.arange(1,10).reshape(3,3)
print(a.sum()) #axis = None
print(np.sum(a))
print(a)
b = a.sum(axis = 0)
print(b)
c = a.sum(axis = 1)
print(c)

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [27]:
#최댓값: [ndarray 배열 객체].max(), np.max()
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.max(),np.max(a)) #axis = None
print(a.max(axis = 0), np.max(a, axis=0))
print(a.max(axis = 1), np.max(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


In [28]:
#최솟값: [ndarray 배열 객체].min(), np.min()
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.min(), np.min(a)) #axis = None
print(a.min(axis = 0), np.min(a, axis = 0))
print(a.min(axis = 1), np.min(a, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 1
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [31]:
#평균과 중앙값: [ndarray 배열 객체].mean(), np.mean() / np.median()
a = np.arange(1, 10).reshape(3,3)
print(a)
print(a.mean(), np.mean(a)) #axis = None
print(a.mean(axis = 0), np.mean(a, axis = 0))
print(a.mean(axis = 1), np.mean(a, axis = 1))
print(np.median(a)) #중앙값은 [ndarray 배열 객체].median() 불가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]
5.0


In [32]:
#표준편차: [ndarray 배열 객체].std(), np.std()
a = np.arange(1, 10).reshape(3,3)
print(a)
print(a.std(), np.std(a)) #axis = None
print(a.std(axis = 0), np.std(a, axis = 0))
print(a.std(axis = 1), np.std(a, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


### 브로드캐스팅 연산
- shape가 같은 두 배열의 이항연산 = 배열의 요소별로 진행
- shape가 다른 두 배열의 이항연산 = 두 배열 간의 형상을 맞추는 Broadcasting 진행
- 브로드캐스팅: 어떤 조건만 만족한다면 모양이 다른 배열끼리 연산 가능, 모양이 부족한 부분은 확장하여 연산 수행

In [33]:
#브로드캐스팅 개념

#사용하지 않은 경우
x = np.array([1,2,3,4,5])
y = np.array([1,1,1,1,1])
print(x+y)
#사용한 경우
y = 1 # 1 하나인데 확장해서 계산
print(x+y)

[2 3 4 5 6]
[2 3 4 5 6]


### shape가 다른 두 배열의 연산
- shape가 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생
- 두 배열을 같은 shape로 만든 후 연산 시행

In [36]:
# Case 1 = 배열과 스칼라
a = np.arange(1,25).reshape(4,6)
print(a + 100) #브로드캐스팅
print('---------------------------------')
#step 1: 스칼라 배열 변경
new_arr = np.full_like(a, 100)
print(new_arr)
print('---------------------------------')
#step 2: 배열 이항 연산
print(a+new_arr)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
---------------------------------
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
---------------------------------
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [37]:
# Case2 = Shape가 다른 배열들의 연산
a = np.arange(5).reshape(1,5)
print(a)
print('---------------------------------')
b = np.arange(5).reshape(5,1)
print(b)
print('---------------------------------')
print(a + b) #브로드캐스팅

[[0 1 2 3 4]]
---------------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
---------------------------------
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [38]:
# 벡터 연산
import numpy as np
import time
a = np.arange(10000000)
result = 0
s = time.time()
for v in a:
    result += v
e = time.time()
print(result, e-s) #반복문 연산 소요 시간
s = time.time()
result = np.sum(a) #벡터 연산
e = time.time()
print(result, e-s) #벡터 연산 수행시간

49999995000000 0.7105767726898193
49999995000000 0.0017080307006835938
